### ISSUE TITLE
Issue when running logpyZebra.py

### ISSUE THREAD

**Issue by murray3** [logpy/logpy#60] opened 2017-03-19 03:19 UTC
I tried running the zebra problem example and got the following error:
~/Documents/dev/logic/logpyZebra.py
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cjm/Documents/dev/logic/logpyZebra.py", line 58, in <module>
    (membero,	(var(), var(), var(), 'zebra', var()), houses)
  File "/Users/cjm/Documents/dev/logic/logpy/core.py", line 53, in lall
    return (lallgreedy, ) + tuple(earlyorder(*goals))
  File "/Users/cjm/Documents/dev/logic/logpy/core.py", line 155, in earlyorder
    groups = groupby(earlysafe, goals)
  File "/Users/cjm/Documents/dev/logic/toolz/itertoolz.py", line 93, in groupby
    d[key(item)](item)
  File "/Users/cjm/Documents/dev/logic/logpy/core.py", line 138, in earlysafe
    goaleval(goal)
  File "/Users/cjm/Documents/dev/logic/logpy/core.py", line 300, in goaleval
    return find_fixed_point(evalt, goal)
  File "/Users/cjm/Documents/dev/logic/logpy/core.py", line 285, in find_fixed_point
    cur = f(cur)
  File "/Users/cjm/Documents/dev/logic/logpy/util.py", line 84, in evalt
    return t[0](*t[1:])
  File "/Users/cjm/Documents/dev/logic/logpyZebra.py", line 9, in lefto
    return membero((q,p), zip(list, list[1:]))
TypeError: 'Var' object has no attribute '__getitem__'

**Comment by lucaswiman** [comment] 2017-03-19 03:26
Duplicate of #58, fixed in #59. The new package name is `kanren`, not `logic`.

**Closed by lucaswiman** 2017-03-19 03:26 UTC
