### ISSUE TITLE
Relation bug?

### ISSUE THREAD

**Issue by andrewchambers** [logpy/logpy#33] opened 2014-04-08 01:04 UTC
```
def test_logic():
    from logpy import run,var,Relation,fact
    valido = Relation()
    fact(valido,"a","b")
    fact(valido,"b","a")
    x = var()
    assert run(0,x, valido(x,x)) == ()

E       assert ('a', 'b') == ()
E         Left contains more items, first extra item: 'a'
```

**Comment by lucaswiman** [comment] 2016-05-03 20:40
I think this is caused by a bug here: https://github.com/logpy/logpy/blob/98e8998c87cc47d1cac835b315a23c79ce0d8f3e/logpy/facts.py#L46

When this is executed, the dict is constructed by zipping together `(~_1, ~_1)` and `('b', 'a')`, which is evaluates to `{'b', 'a')}`, since the `~_1: 'b'` constraint gets overwritten. This is an easy mistake to make when managing constraints in Python (since dicts are a natural choice of data structure). I had a bug with the same cause `django-predicate` last month.

I hope to have a fix for this in the next few days, but figured I'd comment with the cause in case I don't get around to submitting a PR.

**Closed** 2016-05-05 14:01 UTC
